from setuptools import setup, find_packages
exec(open('DynaGen/version.py').read())

setup(
  name = 'DynaGen',
  packages = find_packages(exclude=[]),
  include_package_data = True,
  version = __version__,
  license='MIT',
  description = 'DynaGen - model dynamic processes',
  author = 'Markus J Buehler',
  author_email = 'mbuehler@MIT.EDU',
  long_description_content_type = 'text/markdown',
  url = 'https://github.com/lamm-mit/DynaGen',
  keywords = [
    'artificial intelligence',
    'deep learning',
    'transformers',
    'scientific machine learning',
    'dynamical processes',
    'denoising-diffusion',
    'materials science'
  ],
  install_requires=[
    'accelerate',
    'click',
    'einops>=0.4',
    'einops-exts',
    'ema-pytorch>=0.0.3',
    'fsspec',
    'kornia',
    'numpy',
    'packaging',
    'pillow',
    'pydantic',
    'pytorch-lightning',
    'pytorch-warmup',
    'sentencepiece',
    #'torch>=1.6',
    'torch==1.13.1', 
    'torchvision',
    'transformers',
    'tqdm',
    'jupyterlab',
    'matplotlib',
    'scikit-learn',
    'pandas',
    'IProgress',
    'ipywidgets',
    'opencv-python',

  ],
  classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
  ],
)
